name: Bug report
description: Report a reproducible bug
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please include enough detail for us to reproduce the issue.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Exact commands and context used to reproduce.
      placeholder: |
        1. Activate environment
        2. Run command ...
        3. Observe error ...
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, Python version, and dependency context.
      placeholder: "macOS 15, Python 3.12, requirements.txt installed"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs/output
      description: Paste terminal output or traceback.
      render: shell
